


print(" ")
print("❗☢️CHEATSHEET☢️❗")
print(" ")
print("📂GOBAL")
print(":h[elp] keyword - open help for keyword")
print(":sav[eas] file - save file as")
print(":clo[se] - close current pane")
print(":ter[minal] - open a terminal window")
print(":w newname Save a copy of the current file as ‘newname,’ but continue editing the original file")
print("ZZ - save and close the file")
print(":colorscheme [space]+Ctrl+d – list available Vim color scheme")
print(" ")
print("📂WORKING WITH MULTIPLE FILES")
print(":e file_name  – open a file in a new buffer")
print(":bn  – move to the next buffer")
print(":bp – go back to previous buffer")
print(":bd  – close buffer")
print(":b#  – move to the specified buffer (by number)")
print(":b file_name – move to a buffer (by name)")
print(":ls – list all open buffers")
print(":sp file_name  – open a file in a new buffer and split viewport horizontally")
print(":vs file_name  – open a file in a new buffer and split viewport vertically")
print(":vert ba  – edit all files as vertical viewports")
print(":tab ba  – edit all buffers as tabs")
print("gt – move to next tab")
print("gT – move to previous tab")
print("Ctrl+wq – quit a viewport")
print("Ctrl+= – make all viewports equal in height and width")
print(" ")
print("📂MOVEMENT")
print("H - Top line on screen")
print("M - Middle line on screen")
print("L - Bottom line on screen")
print("W - jump forwards to the start of a word (words can contain punctuation)")
print("E - jump forwards to the end of a word (words can contain punctuation) ")
print("B - jump backwards to the start of a word (words can contain punctuation)")
print("ge - jump backwards to the end of a word")
print("gE - jump backwards to the end of a word (words can contain punctuation)")
print("% - move to matching character (default supported pairs: '()', '{}', '[]'")
print(":# – move to a specified line number (replace # with the line number)")
print("gg - Go to the top of the page")
print("G - Go the bottom of the page")
print("{ } - Go forward and back by paragraph (the next blank line)")
print(" ")
print("📂SELECTING")
print("vi ddqt,[,( -")
print("")
print("")
print(" ")
print("📂EDITING")
print("c - Delete, then start insert mode")
print("cc - Delete line, then start insert mode")
print("C / c$ – replace from the cursor to the end of a line")
print("I / A - Start insert mode at the beginning/end of the line")
print("ea – insert text at the end of the word")
print("J – merge the line below to the current one with a space in between them")
print("gJ – merge the line below to the current one with no space in between them")
print("s – delete a character (and move into insert mode)")
print("")
print(" ")
